services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fuhrparkmanagement'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  auth-service:
    image: 'eclipse-temurin:17-jdk'
    volumes:
      - './auth-service/auth-service.jar:/auth-service.jar'
    ports:
      - '8082:8082'
    command: ['java', '-jar', '/auth-service.jar']
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025