services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fuhrparkmanagement'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  auth-service:
    image: 'eclipse-temurin:17-jdk'
    volumes:
      - './auth-service/auth-service.jar:/auth-service.jar'
    ports:
      - '8082:8082'
    command: ['java', '-jar', '/auth-service.jar']
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/fuhrparkmanagement'
      USER-MANAGEMENT-API_URL: 'http://auth-service:8082'
      SPRING_MAIL_HOST: 'mailhog'
    ports:
      - 8080:8080
  frontend:
    build:
      context: app
      dockerfile: ./Dockerfile
    ports:
      - 4200:80