openapi: "3.0.3"
info:
  title: "Fuhrparkmanagement API"
  description: "Fuhrparkmanagement API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
tags:
  - name: Cars
    description: Cars with their attributes
  - name: Rides
    description: Combines rides with resevations
  - name: Reservations
    description: Reservation
  - name: Statistics
    description: Statistics; driven kilometers
paths:
  /cars:
    get:
      tags:
        - Cars
      summary: "GET cars"
      operationId: "listAll"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Car"
        "403":
          description: "Forbidden"
    post:
      tags:
        - Cars
      summary: "POST cars"
      operationId: "create"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Car"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Car"
        "400":
          description: "Bad Request"
        "403":
          description: "Forbidden"
  /cars/{id}:
    get:
      tags:
        - Cars
      summary: "GET cars/{id}"
      operationId: "find"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Car"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
    put:
      tags:
        - Cars
      summary: "PUT cars/{id}"
      operationId: "update"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Car"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Car"
        "400":
          description: "Bad Request"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
    delete:
      tags:
        - Cars
      summary: "DELETE cars/{id}"
      operationId: "delete"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /rides:
    get:
      tags:
        - Rides
      summary: "GET rides"
      operationId: "listAll"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ride"
        "403":
          description: "Forbidden"
    post:
      tags:
        - Rides
      summary: "POST rides"
      operationId: "create"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ride"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Ride"
        "400":
          description: "Bad Request"
        "403":
          description: "Forbidden"
  /rides/{id}:
    get:
      tags:
        - Rides
      summary: "GET rides/{id}"
      operationId: "find"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Ride"
        "403":
          description: "Forbidden"
    put:
      tags:
        - Rides
      summary: "PUT rides/{id}"
      operationId: "update"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ride"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Ride"
        "400":
          description: "Bad Request"
        "403":
          description: "Forbidden"
    delete:
      tags:
        - Rides
      summary: "DELETE rides/{id}"
      operationId: "delete"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
        "403":
          description: "Forbidden"
  /reservations:
    get:
      tags:
        - Reservations
      summary: "GET reservations"
      operationId: "listAll"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Reservation"
        "403":
          description: "Forbidden"
    post:
      tags:
        - Reservations
      summary: "POST reservations"
      operationId: "create"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Reservation"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Reservation"
        "400":
          description: "Bad Request"
        "403":
          description: "Forbidden"
  /reservations/{id}:
    get:
      tags:
        - Reservations
      summary: "GET reservations/{id}"
      operationId: "find"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Reservation"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
    put:
      tags:
        - Reservations
      summary: "PUT reservations/{id}"
      operationId: "update"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Reservation"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Reservation"
        "403":
          description: "Forbidden"
    delete:
      tags:
        - Reservations
      summary: "DELETE reservations/{id}"
      operationId: "delete"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /statistics/users:
    get:
      tags:
        - Statistics
      summary: "GET statistics/users"
      operationId: "listAll"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Statistic"
        "403":
          description: "Forbidden"
  /statistics/users/{id}:
    get:
      tags:
        - Statistics
      summary: "GET statistics/users/{id}"
      operationId: "find"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Statistic"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
components:
  schemas:
    Car:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        licensePlate:
          type: "string"
        modelName:
          type: "string"
        fuelType:
          type: "string"
          enum:
            - "PETROL"
            - "DIESEL"
            - "ELECTRIC"
        location:
          type: "string"
        seats:
          type: "integer"
          format: "int32"
          minimum: 1
        range:
          type: "integer"
          format: "int32"
          minimum: 1
        available:
          type: "boolean"
          default: true
        createdDate:
          type: string
          format: date-time
          readOnly: true
        deletedDate:
          type: string
          format: date-time
          readOnly: true
      required:
        - licensePlate
        - modelName
        - fuelType
        - location
        - seats
        - range
    Ride:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        carId:
          type: "integer"
          format: "int64"
        startAddress:
          type: "string"
        destinationAddress:
          type: "string"
        startDate:
          type: "string"
          format: "date-time"
        endDate:
          type: "string"
          format: "date-time"
        purpose:
          type: "string"
        createdDate:
          type: string
          format: date-time
          readOnly: true
        deletedDate:
          type: string
          format: date-time
          readOnly: true
      required:
        - carId
        - startAddress
        - destinationAddress
        - startDate
        - endDate
        - purpose
    Reservation:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        userId:
          type: "string"
        rideId:
          type: "integer"
          format: "int64"
        createdDate:
          type: string
          format: date-time
        deleted_date:
          type: string
          format: date-time
      required:
        - userId
        - rideId
    Statistic:
      type: object
      properties:
        kilometers:
          type: "string"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []